apiVersion: v1
kind: Service
metadata:
  labels:
    app: application-02
  name: application-02
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: application-02
  type: ClusterIP
