apiVersion: v1
kind: Service
metadata:
  labels:
    app: application-01
  name: application-01
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: application-01
  type: ClusterIP
